######################################################################
# Automatically generated by qmake (3.0) ?? ???. 17 23:47:01 2017
######################################################################

TEMPLATE = app
TARGET = qt-1.1
INCLUDEPATH += .
QT += gui widgets


# Input
SOURCES += qt-1.1.cpp
